# Generated by Django 4.0.4 on 2023-05-16 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Apiscall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DirecterDetails',
            fields=[
                ('dirid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('you_check_it', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employeemodel',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('salary', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Intrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('interests', models.ManyToManyField(to='demo.intrest')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sportsmodel',
            fields=[
                ('sportid', models.IntegerField(primary_key=True, serialize=False)),
                ('sportname', models.CharField(max_length=150)),
                ('sporttimeing', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'sports',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Studentmodel',
            fields=[
                ('stid', models.IntegerField(primary_key=True, serialize=False)),
                ('stname', models.CharField(max_length=100)),
                ('total_present', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('behavior', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterface3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('note', models.CharField(max_length=244)),
                ('user', models.ManyToManyField(related_name='userpoint3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterface2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('note', models.CharField(max_length=244)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpoint2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterface1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('note', models.CharField(max_length=244)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userpoint', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=244)),
                ('duration', models.IntegerField()),
                ('Person', models.ManyToManyField(to='demo.person')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sungby', to='demo.singer')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=244)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.city')),
                ('interests', models.ManyToManyField(to='demo.intrest')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demo.person')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='demo.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Marksmodel',
            fields=[
                ('Marksid', models.IntegerField(primary_key=True, serialize=False)),
                ('maths', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('computers', models.IntegerField()),
                ('EmployeeDetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeDetail', to='demo.employeedetails')),
                ('directorDetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directorDetail', to='demo.directerdetails')),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='demo.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks1', to='demo.album')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('album', 'order')},
            },
        ),
    ]
